server:
  port: 11996
spring:
  application:
    name: cloud-test1
  #data:
    #mongodb:

     # uri: mongodb://root:123@120.76.84.42:27017/test
     # host: 120.76.84.42
     # port: 27017
     # password: 123
     # username: root
     # database: admin
     # authentication-database: trjwowbox
#security:
#    authorization: enabled


mongodb:
  uri: 120.76.84.42:27017
  password: 123
  usernmae: root
  databasename: admin

eureka:
  client:
    service-url:
      defaultZone: http://demo:actuator@localhost:8761/eureka
