server:
  port: 11996
spring:
  application:
    name: cloud-test1
  data:
    mongodb:
      uri: mongodb://root:123@120.76.84.42:27017/trjwowbox
      password: 123
      username: root


mongodb:
  uri: 120.76.84.42:27017
  password: 123
  usernmae: root
  databasename: trjwowbox

eureka:
  client:
    service-url:
      defaultZone: http://demo:actuator@localhost:8761/eureka
