server:
  port: 11994
spring:
  application:
    name: cloud-zuul-api

zuul:
  routes:
   usertest:
    path: /api-a/**
    service-id: cloud-test2

#zuul:
#  routes:
#   usertest:
#    path: /api-b/**
#    service-id: cloud-test1

eureka:
  client:
    service-url:
      defaultZone: http://demo:actuator@localhost:8761/eureka
